### PR TITLE
add event for gov proposal and validatebasic

### PR DESCRIPTION
**Pull request by DongLieu**

### CODE REVIEW

**Comment by jiujiteiro** [comment]
@catShaark @DongLieu we have some of the gov proposal handler and tests already here: https://github.com/realiotech/multi-staking/blob/main/x/multi-staking/types/proposal.go
https://github.com/realiotech/multi-staking/blob/main/x/multi-staking/types/proposal_test.go
https://github.com/realiotech/multi-staking/blob/main/x/multi-staking/proposal_handler.go

What is the reason this is being changed?

**Comment by catShaark** [comment]
We just wanna add some minor stuffs like validate func for each proposal type, and including more events. These changes won't break the current gov logic.

**Comment by jiujiteiro** [comment]
@catShaark thanks! It looks like the main and refactor branch are not in sync. We have for example and events file already (https://github.com/realiotech/multi-staking/blob/main/x/multi-staking/types/events.go) 

and also some of the validate
(https://github.com/realiotech/multi-staking/blob/main/x/multi-staking/types/proposal.go#L55)

maybe we should merge main into refactor

**Comment by jiujiteiro** [comment]
Check out pr #26. Those changes are not in the refactor branch.

**Comment by catShaark** [comment]
I just merged main into refactor, which include all changes in pr #26 to refactor https://github.com/realiotech/multi-staking/commit/16578415ddc355c914a668712fd8bf32235899d8#diff-d92cc6d729e5391e103a7ec8559bece396fe23b688fb45197236f1299448f7cc

**Comment by DongLieu** [comment]
I think this PR should be closed

**Pull request closed without merging**
