### PR TITLE
Add Swagger documentation for multi-staking module

### PR DESCRIPTION
**Pull request by MasterPi-2124**

### CODE REVIEW

**Review by jiujiteiro — APPROVED** [review]

**Review by jiujiteiro — CHANGES_REQUESTED** [review]
Lets get this issue here done and then update the swagger docs with the new endpoint:

https://github.com/realiotech/multi-staking/issues/134

**Comment by jiujiteiro** [comment]
@MasterPi-2124 left a comment

**Comment by MasterPi-2124** [comment]
Sure let me update the doc

**Review by jiujiteiro — APPROVED** [review]
lgtm

**Pull request merged**
